### ISSUE TITLE
Auto log out

### ISSUE THREAD

**Issue by srdo96** [Bugswriter/arch-linux-magic#6]
When I click a website link in the browser my laptop auto-logout. Not for all websites. some specific websites. For example: if I click the patch GitHub link (https://github.com/ds300/patch-package) my laptop auto-logout.

**Comment by r4vanan** [comment]
same here for some vido on youtube it logsout i dont know why it is happening

**Comment by r4vanan** [comment]
libxft-bgra-git (AUR)
and ttf-joypixel (from pacman)
it is working for me bro @srdo96

**Comment by srdo96** [comment]
> libxft-bgra-git (AUR) and ttf-joypixel (from pacman) it is working for me bro @srdo96

Its worked. Thanks a lot, bro. But why did this problem occur?
